name: fast api pipline
on:
  push:
    branches:
      - feature/shah
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4 
      - name: build docker image
        run: |
          docker build -t fast-api:${{ github.sha}} .
          echo running docker ls
          docker image ls