name: FastAPI CI/CD

on:
  push:
    branches:
      - feature/shah

env:
  AWS_REGION: us-east-1
  ECR_REPO: shah
  CLUSTER_NAME: fastapi-cluster
  IMAGE_TAG: ${{ github.sha }}

jobs:

#------- CI ----------------

  ci:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::929368846026:role/role-oidc-second
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t $ECR_REPO:$IMAGE_TAG .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: ECR login
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push image
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG \
          ${{ steps.login.outputs.registry }}/$ECR_REPO:$IMAGE_TAG
          docker push \
          ${{ steps.login.outputs.registry }}/$ECR_REPO:$IMAGE_TAG



  cd:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::929368846026:role/role-oidc-second
          aws-region: ${{ env.AWS_REGION }}

          # Connect to the EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      # Installing   Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      #### Deploying
      - name: Helm deploy
        run: |
          helm upgrade --install fastapi ./helm \
            --set image.repository=${{ steps.login.outputs.registry }}/$ECR_REPO \
            --set image.tag=$IMAGE_TAG
